# Read about `build.yaml` at https://pub.dartlang.org/packages/build_config
targets:
  $default:
    builders:
      json_serializable:
        generate_for:
          include:
          - example/example.**
          - benchmark/src/stats.**
