name: json_alt
version: 0.1.0-dev
description: A starting point for Dart libraries or applications.

environment:
  sdk: '>=2.9.0 <3.0.0'

dependencies:
  charcode: ^1.1.3
  json_annotation: ^3.1.1
  meta: ^1.2.4

dev_dependencies:
  build_runner: ^1.10.6
  json_serializable: ^3.5.0
  pedantic: ^1.9.0
  test: ^1.15.7
  jsontool:
