name: json_alt
version: 0.1.0-dev
description: A starting point for Dart libraries or applications.

environment:
  sdk: '>=2.9.0 <3.0.0'

dependencies:
  charcode: ^1.1.1
  json_annotation: ^2.0.0
  meta: ^1.1.0

dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^2.0.1
  pedantic: ^1.9.0
  test: ^1.3.0
